version: '3.9'

services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf:/etc/mysql/conf.d
      - ./requirements/mariadb/tools/initdb:/docker-entrypoint-initdb.d
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/tools/certificate:/etc/nginx/ssl
    networks:
      - inception

volumes:
  wordpress_data:
  mariadb_data:

networks:
  inception:
    driver: bridge